version: '3.7'
services:
  graphql-mongodb:
    image: mongo
    container_name: graphql-mongodb
    restart: always
    # caso queira variavel de ambiente
    environment: 
      MONGO_INITDB_DATABASE: school
      # MONGO_INITDB_ROOT_DATABASE: admin
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - .:/database/mongodb
    logging:
      driver: none